### ISSUE TITLE
NEW INDEX: ENDVI

### ISSUE THREAD

**Issue by gagev** [awesome-spectral-indices/awesome-spectral-indices#44]
Please, complete the following information:

```python
ENDVI=SpectralIndex(
    short_name='ENDVI',
    long_name='Enhanced Normalized Difference Vegetation Index',
    formula='((N + G) - (2 * B)) / ((N + G) + (2 * B))',
   reference='http://dx.doi.org/10.1088/1755-1315/145/1/012012',
    application_domain='vegetation',
    date_of_addition='2024-03-29',
    contributor="https://github.com/gagev"
)
```

**Comment by davemlz** [comment]
Hi @gagev,

Thank you for your contribution!

The paper you are referencing here doesn't seem to be the original source paper of the index. I've been searching for it but I wasn't able to find it. If you find the original source paper, please update this issue for further acceptance of the index.

Cheers!

David

**Comment by j-miszczyszyn** [comment]
Hello @davemlz 
@gagev is talking about this one:
https://maxmax.com/maincamerapage/remote-sensing/enhanced-normalized-difference-vegetation-index

I did a little research and I suspect that the authors of this indicator have not written a publication on the subject. I believe so because the publications in which I came across ENDVI cite the maxmax.com website as a reference, but the lack of a scientific article did not prevent the authors of these publications from basing their research on this indicator. 
I https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0186193
https://www.mdpi.com/2072-4292/12/3/387#B32-remotesensing-12-00387

Regards,
Jakub

**Comment by davemlz** [comment]
Thank you for the research, @j-miszczyszyn!

Indeed, it seems that LDP LLC were the creators, but since there is only a wep page about the index, the URL is not a good reference here since it is not a persistent identifier. However, we can use this one https://doi.org/10.1371/journal.pone.0186193, which is the first paper you mention, and co-authored by LDP LLC.

I will include the index now!

Thank you again!

**Comment by davemlz** [comment]
The index was successfully added and will be available in the next version of ASI! ;)
