### ISSUE TITLE
Sentinel-1 pre-processing steps

### ISSUE THREAD

**Issue by alkimj** [awesome-spectral-indices/awesome-spectral-indices#65]
First of all, thank you for the great contribution regarding this excellent R package. I’m writing to ask whether the Sentinel-1 radar images need to be pre-processed after download or if they are already pre-processed.

Thank you in advance!

**Comment by davemlz** [comment]
Hi! I'm not really sure if you are posting the Issue in the right repository since this is not an R package.

In any case, if what you are looking is for the level of processing of S1 images before computing indices: It will depend on the index. For instance, DpRVIVV requires linear units for its calculation. I would recommend to check the reference of each index ;)

Cheers!
